import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'Models/posts_model.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {

  List<Autogenerated> postList = [];

  Future<List<Autogenerated>> getPostApi () async {
    final response = await http.get(Uri.parse('https://jsonplaceholder.typicode.com/posts'));
    var data = jsonDecode(response.body.toString());
    if(response.statusCode == 200){
    for(Map<dynamic, dynamic> i in data){
      postList.add(Autogenerated.fromJson(i as Map<String, dynamic>));
    }
    return postList;
    }else{
      return postList;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Center(child: Text(
          'API Integration',
          style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: Colors.blue, fontFamily: 'Raleway', letterSpacing: 2),
        )),
      ),
      body: Column(
        children: [
          Expanded(
            child: FutureBuilder(
                future: getPostApi(),
                builder: (context, snapshot){

                    return ListView.builder(
                        itemCount: postList.length,
                        itemBuilder: (context, index){
                      return
                      Card(
                        color: Colors.blue.shade100,
                        child: Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Title', style: TextStyle(fontWeight: FontWeight.bold, color: Colors.red)),
                              Text(postList[index].title.toString()),
                                SizedBox(height: 20),
                              Text('Description', style: TextStyle(fontWeight: FontWeight.bold)),
                              Text(postList[index].body.toString()),
                            ],
                          ),
                        ),
                      );
                    });
                  }
                ),
          )
        ],
      ),
    );
  }
}
